const faker = require('@faker-js/faker');

const currentDate = new Date();
export let clientTasks = [
    /*  {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 1),
        end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 15),
        name: 'Some Project',
        id: 'ProjectSample',
        progress: 25,
        type: 'project',
        displayOrder: 3,
    }, */
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 1),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            2,
            12,
            28
        ),
        name: 'Позвонить клиенту',
        id: 'Task 0',
        progress: 45,
        dependencies: ['1'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 2),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            4,
            0,
            0
        ),
        name: 'Уточнить время доставки',
        id: 'Task 1',
        progress: 25,
        dependencies: ['1'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 4),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            8,
            0,
            0
        ),
        name: 'Оформить заявку',
        id: 'Task 2',
        progress: 10,
        dependencies: ['2'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 8),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            9,
            0,
            0
        ),
        name: 'Перезвонить клиенту',
        id: 'Task 3',
        progress: 2,
        dependencies: ['2'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 9),
        end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 10),
        name: 'Review',
        id: 'Task 4',
        type: 'task',
        progress: 70,
        dependencies: ['3'],
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 1),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            2,
            12,
            28
        ),
        name: 'Позвонить клиенту',
        id: 'Task 0',
        progress: 45,
        dependencies: ['4'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 3),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            4,
            0,
            0
        ),
        name: 'Уточнить время доставки',
        id: 'Task 1',
        progress: 25,
        dependencies: ['5'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 5),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            8,
            0,
            0
        ),
        name: 'Оформить заявку',
        id: 'Task 2',
        progress: 10,
        dependencies: ['6'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 8),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            9,
            0,
            0
        ),
        name: 'Перезвонить клиенту',
        id: 'Task 3',
        progress: 2,
        dependencies: ['7'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 8),
        end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 10),
        name: 'Review',
        id: 'Task 4',
        type: 'task',
        progress: 70,
        dependencies: ['8'],
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 1),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            2,
            12,
            28
        ),
        name: 'Позвонить клиенту',
        id: 'Task 0',
        progress: 45,
        dependencies: ['10'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 2),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            4,
            0,
            0
        ),
        name: 'Уточнить время доставки',
        id: 'Task 1',
        progress: 25,
        dependencies: ['11'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 4),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            8,
            0,
            0
        ),
        name: 'Оформить заявку',
        id: 'Task 2',
        progress: 10,
        dependencies: ['12'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 8),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            9,
            0,
            0
        ),
        name: 'Перезвонить клиенту',
        id: 'Task 3',
        progress: 2,
        dependencies: ['13'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 8),
        end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 10),
        name: 'Review',
        id: 'Task 4',
        type: 'task',
        progress: 70,
        dependencies: ['14'],
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 1),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            2,
            12,
            28
        ),
        name: 'Позвонить клиенту',
        id: 'Task 0',
        progress: 45,
        dependencies: ['15'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 2),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            4,
            0,
            0
        ),
        name: 'Уточнить время доставки',
        id: 'Task 1',
        progress: 25,
        dependencies: ['16'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 4),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            8,
            0,
            0
        ),
        name: 'Оформить заявку',
        id: 'Task 2',
        progress: 10,
        dependencies: ['16'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 8),
        end: new Date(
            currentDate.getFullYear(),
            currentDate.getMonth(),
            9,
            0,
            0
        ),
        name: 'Перезвонить клиенту',
        id: 'Task 3',
        progress: 2,
        dependencies: ['17'],
        type: 'task',
        project: 'ProjectSample',
        displayOrder: 3,
    },
    {
        start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 8),
        end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 10),
        name: 'Review',
        id: 'Task 4',
        type: 'task',
        progress: 70,
        dependencies: ['17'],
        project: 'ProjectSample',
        displayOrder: 3,
    },
];
export let clients = [
    {
        id: '1',
        title: 'CDD1049',
        amount: 30.5,
        customer: 'Ekaterina Tankova',
        date: '2022-06-19',
        status: 'Pending',
        statusId: 1,
        email: faker.internet.email(),
        phone: '',
    },
    {
        id: '2',
        title: 'CDD1048',
        amount: 25.1,
        customer: 'Cao Yu',
        date: '2022-06-18',
        status: 'Delivered',
        email: faker.internet.email(),
        statusId: 1,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '3',
        title: 'CDD1047',
        amount: 10.99,
        customer: 'Alexa Richardson',
        date: '2022-05-12',
        status: 'Refunded',
        email: faker.internet.email(),
        statusId: 1,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '4',
        title: 'CDD1046',
        amount: 96.43,
        customer: 'Anje Keizer',
        date: '2022-06-18',
        status: 'Pending',
        email: faker.internet.email(),
        statusId: 2,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '5',
        title: 'CDD1045',
        amount: 32.54,
        customer: 'Clarke Gillebert',
        date: '2022-06-22',
        status: 'Delivered',
        email: faker.internet.email(),
        statusId: 2,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '6',
        title: 'CDD1044',
        amount: 16.76,
        customer: 'Adam Denisov',
        date: '2022-06-05',
        status: 'Delivered',
        email: faker.internet.email(),
        statusId: 3,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '7',
        title: 'CDD1049',
        amount: 30.5,
        customer: 'Ekaterina Tankova',
        date: '2022-06-11',
        status: 'Pending',
        email: faker.internet.email(),
        statusId: 3,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '8',
        title: 'CDD1048',
        amount: 25.1,
        customer: 'Cao Denisov',
        date: '2022-06-12',
        status: 'Delivered',
        email: faker.internet.email(),
        statusId: 4,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '9',
        title: 'CDD1047',
        amount: 10.99,
        customer: 'Ekaterina Richardson',
        date: '2022-06-25',
        status: 'Refunded',
        email: faker.internet.email(),
        statusId: 2,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '10',
        title: 'CDD1046',
        amount: 96.43,
        customer: 'Clarke Keizer',
        date: '2022-06-17',
        status: 'Pending',
        email: faker.internet.email(),
        statusId: 4,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '11',
        title: 'CDD1045',
        amount: 32.54,
        customer: 'Adam Gillebert',
        date: '2022-06-22',
        status: 'Delivered',
        email: faker.internet.email(),
        statusId: 5,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '12',
        title: 'CDD1044',
        amount: 16.76,
        customer: 'Anje Denisov',
        date: '2022-06-27',
        status: 'Delivered',
        email: faker.internet.email(),
        statusId: 6,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '13',
        title: 'CDD1049',
        amount: 30.5,
        customer: 'Ekaterina Tankova',
        date: '2022-06-19',
        status: 'Pending',
        email: faker.internet.email(),
        statusId: 1,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '14',
        title: 'CDD1048',
        amount: 25.1,
        customer: 'Cao Yu',
        date: '2022-06-18',
        status: 'Delivered',
        email: faker.internet.email(),
        statusId: 1,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '15',
        title: 'CDD1047',
        amount: 10.99,
        customer: 'Alexa Richardson',
        date: '2022-05-12',
        status: 'Refunded',
        email: faker.internet.email(),
        statusId: 1,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '16',
        title: 'CDD1046',
        amount: 96.43,
        customer: 'Anje Keizer',
        date: '2022-06-18',
        status: 'Pending',
        email: faker.internet.email(),
        statusId: 2,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '17',
        title: 'CDD1045',
        amount: 32.54,
        customer: 'Clarke Gillebert',
        date: '2022-06-22',
        status: 'Delivered',
        email: faker.internet.email(),
        statusId: 2,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '18',
        title: 'CDD1044',
        amount: 16.76,
        customer: 'Adam Denisov',
        date: '2022-06-05',
        status: 'Delivered',
        email: faker.internet.email(),
        statusId: 3,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '19',
        title: 'CDD1049',
        amount: 30.5,
        customer: 'Ekaterina Tankova',
        date: '2022-06-11',
        status: 'Pending',
        email: faker.internet.email(),
        statusId: 3,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '20',
        title: 'CDD1048',
        amount: 25.1,
        customer: 'Cao Denisov',
        date: '2022-06-12',
        status: 'Delivered',
        email: faker.internet.email(),
        statusId: 4,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '21',
        title: 'CDD1047',
        amount: 10.99,
        customer: 'Ekaterina Richardson',
        date: '2022-06-25',
        status: 'Refunded',
        email: faker.internet.email(),
        statusId: 2,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '22',
        title: 'CDD1046',
        amount: 96.43,
        customer: 'Clarke Keizer',
        date: '2022-06-17',
        status: 'Pending',
        email: faker.internet.email(),
        statusId: 4,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '23',
        title: 'CDD1045',
        amount: 32.54,
        customer: 'Adam Gillebert',
        date: '2022-06-22',
        status: 'Delivered',
        email: faker.internet.email(),
        statusId: 5,
        phone: faker.phone.phoneNumber(),
    },
    {
        id: '24',
        title: 'CDD1044',
        amount: 16.76,
        customer: 'Anje Denisov',
        date: '2022-06-27',
        status: 'Delivered',
        email: faker.internet.email(),
        statusId: 6,
        phone: faker.phone.phoneNumber(),
    },
];
